### ISSUE TITLE
How to use this Bundle ?

### ISSUE THREAD

**Issue by puterakahfi** [symfony-bundles/redis-bundle#15]
Hi,
I have installed this bundle on Symfony 4
but looks like the configuration not passed to client, it's always pointing to 127.0.0.1 

here my .env config 

REDIS_URL=tcp://asdocker-redis:6379?database=0

my controller 
use  SymfonyBundles\RedisBundle\Redis;

$redis = new Redis\Client();

but, I always get connection refused response 

"Connection refused [tcp://127.0.0.1:6379]",

is there something miss in my configuration ?

Thanks
Kahfi

**Comment by khaperets** [comment]
Hi!

You need to embed a client through DependencyInjection. For example:
```php
public function testAction(Redis\Client $redis)
{
$redis->...
}
```
