### ISSUE TITLE
A tree builder without a root node is deprecated since Symfony 4.2

### ISSUE THREAD

**Issue by codegain** [symfony-bundles/redis-bundle#16]
Getting this deprecation notice on 4.3.9:

`A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.`

in

```
vendor/symfony-bundles/redis-bundle/DependencyInjection/Configuration.php:15
    › {
    ›     $builder = new TreeBuilder();
    ›     $builder
  }
```

**Comment by codegain** [comment]
Related:

`The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "sb_redis" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.`

**Comment by khaperets** [comment]
Thank you for your message.
Pull request #17 merged.
