### ISSUE TITLE
Fixed return type missing deprecation in getConfigTreeBuilder()

### ISSUE THREAD

**Issue by palanisamy-emis** [symfony-bundles/redis-bundle#40]
Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration in the future. Do the same in implementation "SymfonyBundles\RedisBundle\DependencyInjection\Configuration" now to avoid errors or add an explicit @return annotation to suppress this message.

**Comment by Yozhef** [comment]
thanks, we added a clear return

**Comment by palanisamy-emis** [comment]
> Feat/add return type get config tree builder #41

When will you take a release for this PR @Yozhef

**Comment by Yozhef** [comment]
@palanisamy-emis of course, released 3.1.5
