### ISSUE TITLE
Could we bump req to allow use the bundle in SF 4 ?

### ISSUE THREAD

**Issue by tabbi89** [symfony-bundles/redis-bundle#6]

**Comment by khaperets** [comment]
Now I'm working for this fix in the new version of bundle.

**Comment by tabbi89** [comment]
+1

**Comment by khaperets** [comment]
Release 2.0 is ready ;)

**Comment by waghanza** [comment]
EDIT : I just resolved ;-) I was using a wrong namespace in my `class`
